# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}

title: Dota2MM
email: git@myan.app

# Build settings
# markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed


exclude:
  - LICENSE
  - CNAME