# command >> bundle exec jekyll serve'
# {{ page.title }} || {{ site.title }}
# {{ site.myvariable }}

title: Dota2MM

encoding: utf-8
timezone: Asia/Rangoon

source: docs/
destination: .test/

plugins: 
  - jekyll-feed
