# command >> bundle exec jekyll serve'
# {{ page.title }} || {{ site.title }}
# {{ site.myvariable }}

title: Dota2MM
email: git@myan.app

encoding: utf-8
timezone: Asia/Rangoon

source: docs/
destination: build/

plugins: 
  - jekyll-admin  
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache

exclude:
  - CNAME
  - LICENSE